<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <!--NuGet package-->
  <PropertyGroup>
    <Product>ObservableView</Product>
    <Description>Sorting, filtering, and grouping enhancements for .NET collections</Description>
    <Version>1.0.0</Version>
    <Authors>Thomas Galliker</Authors>
    <PackageId>ObservableView</PackageId>
    <PackageTags>ObservableView;ObservableCollection;sorting;filtering;searching;collections;xamarin</PackageTags>
    <PackageIcon>logo.png</PackageIcon>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/thomasgalliker/ObservableView</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/thomasgalliker/ObservableView</RepositoryUrl>
    <Company>superdev GmbH</Company>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Copyright>Copyright $([System.DateTime]::Now.ToString(`yyyy`)) © Thomas Galliker</Copyright>
    <PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/../ReleaseNotes.txt"))</PackageReleaseNotes>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedAllSources>true</EmbedAllSources>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="True" PackagePath="\" />
    <None Include="..\LICENSE" Pack="True" PackagePath="\" />
    <None Include="..\logo.png" Pack="True" PackagePath="\" />
  </ItemGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <Target Name="PackBuildOutputs">
    <ItemGroup>
      <!--Add pdbs-->
      <TfmSpecificPackageFile Include="$(OutDir)$(AssemblyName).pdb" PackagePath="lib/netstandard2.0" />

      <!--Add the referenced assembly to the nuget package-->
      <TfmSpecificPackageFile Include="$(OutDir)ObservableView.dll" PackagePath="lib/netstandard2.0" />
      <TfmSpecificPackageFile Include="$(OutDir)ObservableView.pdb" PackagePath="lib/netstandard2.0" />
      <TfmSpecificPackageFile Include="$(OutDir)ObservableView.xml" PackagePath="lib/netstandard2.0" />
    </ItemGroup>
  </Target>
</Project>
